version: '3.8'

services:
  nextjs:
    build: .
    container_name: nextjs_frontend
    network_mode: "host"
    volumes:
      - .:/app
      - /app/node_modules  # Prevents node_modules conflicts
    command: ["pnpm", "dev"]
    env_file:
      - .env
    restart: always

